### ISSUE TITLE
Please considering rename aleph.js

### ISSUE THREAD

**Issue by etcumvt** [alephjs/aleph.js#17]
This is **not** a technical topic.

The name aleph matches Cult(アレフ) in Japan.
https://en.wikipedia.org/wiki/Aleph_(Japanese_cult)

Japanese people are a bit afraid to talk about it.
Concerns about the name have already erupted from the Japanese community.
https://twitter.com/search?q=aleph.js%20lang%3Aja&src=typed_query&f=live

**Comment by ije** [comment]
sorry to hear that, **Aleph** was coming from one of my favorite books [The Aleph  (by Jorge Luis Borges)](http://www.phinnweb.org/links/literature/borges/aleph.html), it means *endless* in the book, i like the idea and it's easy to create an identity.

**Comment by ije** [comment]
anyway i want Aleph.js(for now) is **OS Community** powered, let's discuss about the project name here, you are welcome to give any idea about it, thanks

**Comment by etcumvt** [comment]
Thank you for your consideration.
First of all, please let me make it clear that there is nothing incriminating about community members or the books.

I saw a tweet that said, "This name 'aleph(アレフ)' might be hard to accept in Japan." I agree with this. In Japanese society, pronouncing the word 'aleph(アレフ)' can be a bit intimidating or frightening. People may be surprised to hear it in the streets or restaurants.

**Comment by webdeb** [comment]
@etcumvt maybe this group will rename them self again at some point to "gugl", and then?

**Comment by ije** [comment]
@etcumvt i found there is a food company which name is 「株式会社アレフ」 in Japan.

<img width="326" alt="Screenshot 2020-11-09 at 12 21 47" src="https://user-images.githubusercontent.com/2883484/98499980-26644680-2286-11eb-80f8-97ebed931493.png">

https://www.aleph-inc.co.jp/

**Comment by etcumvt** [comment]
@ije 
As you point out, it matches the name of the company.

There seems to be a spike in visits and inquiries to the website after execution of Death Penalty.
https://www.j-cast.com/2018/07/06333206.html

A staff said.
'It's annoying because impressions are important in the restaurant industry. If we could get rid of it, we'd take steps.

**Comment by jksy** [comment]
I just happened to find it and would like to comment on it.
I'm Japanese and I know of a religious group called Aleph.

In my opinion, just because the name Aleph is frowned upon in Japan, doesn't mean we should change the name used in other countries.

Even if the Japanese don't use it because this name, it's up to alephjs to decide, not us to change it.
I don't mind, though.

If you need it, you can make it up yourself.

**Comment by Ovis** [comment]
I'm Japanese, and I am aware of Aleph and the terrorist organization it was based on.
But I don't think we need to change the name.

There are many languages in the world and they have meaning. This is diversity and should be respected.
If the purpose of naming it is to make fun of it, it's a problem. But otherwise, I don't think it needs to be changed.
There are some words in Japanese that are pronounced in a way that would mean contempt in other countries. Sometimes words that are common in other countries sound like insults in Japan.
It would be difficult to live with these words if you worry about them one by one.
I think we need to understand and respect each other's meanings.

**Comment by engnakagawa** [comment]
例えばv9.1.1のブロダクトがあったとします。アメリカ人はこれを「同時多発テロを想起させる」として避けるのでしょうか？私はそうは思いません。

例えば、誕生日が9月11日の娘がいたとして、同様の理由で、誕生日パーティーを開催することを禁止するのでしょうか。私はそうは思いません。

私はこの問題は同種だと考えています。
9月11はただの日付です。alephはただの単語です。

また、「日本人」は主語として大きすぎます。

よって私はこのissueの方針に反対です。

**Comment by kosaki** [comment]
+1. 
I don't think we need to change.

I am Japanese and I agree "for Japanese" is too much strong.

**Comment by na4zagin3** [comment]
Another Japanese here too.
Whenever I say alephs in mathematical or linguistic contexts, I don’t think of the cult formerly called Aum, with which I think it is more popular because that was the original name they used when they committed the acts of terrorism.

**Comment by JLarky** [comment]
I'm proposing `dext.js` :) as in "deno" instead of "node" :)

**Comment by webdeb** [comment]
omg, aren't there some bugs to fix of some features to contribute?

**Comment by ije** [comment]
@JLarky interesting, in fact there is another module named *dext* in [deno.land](https://deno.land/x/dext).
Admittedly, Aleph.js(for now) is inspired by **next.js**, but i hope the project name is meaningful with strong identity.

**Comment by ije** [comment]
@webdeb i guess need to wait, since Deno is not production ready and Aleph.js is in alpha stage, but welcome to contribute!
FYI please check our **v0.3 roadmap**(#5).

**Comment by ije** [comment]
there some ideas for voting:

- aleph.js (**aleph**, currently)
- postjs (**post**, origin project name [repo](https://github.com/ije/postjs), inspired by *postcss*)
- dxjs (**dx**, deno + jsx)

*(other names are accepted)*

**Comment by nikitalk** [comment]
Maybe dext.js (**de**no + ne**xt**)?

**Comment by shadowtime2000** [comment]
@nikitalk This was already said previously in this issue that their is already a module called [dext](https://deno.land/x/dext@0.9.4).

**Comment by shadowtime2000** [comment]
It doesn't seem like there was much support for changing the name, with it seeming like 3 ppl supporting it while there are like 6 ppl talking about how just for Japanese is "too strong". imo it shouldn't be changed. Also we are already creating a Svelte like framework called [Alef](https://github.com/alephjs/alef-component) with the extension `.alef` which sounds kind of like Aleph so I don't think there is any point in changing it now. This issue has been open for roughly 2 months and I think we should resolve this as soon as possible. @ije What do you think?

**Comment by ije** [comment]
i am going to close this, you may can call it **alephjs** instead of **aleph**, that means it's technical stuff not any cult.

**Comment by KaminoRyo** [comment]
@ije
I am also Japanese, but I agree with the name change.
There will be fatal problems in the spread and development (marketing) in Japan.
Also, because of the incident in the 90's, the reaction differs depending on the generation. It's a nightmare name for people in their thirties and above.
It's like a Japanese Muslim (almost nonexistent) creating a framework called "Al-Qaida.js".
Do you still choose to keep your current name?
Many people are not that logical.  From the fact that they "rejected the offer to rename", some people may speculate that you are a racist. 
I don't know which one to choose, but I think you need to understand these circumstances.
