### ISSUE TITLE
DevTool

### ISSUE THREAD

**Issue by Carthanial** [alephjs/aleph.js#197]
My team and I are looking to make a DevTool for Aleph.js! Is now a good time to do so or should we wait until Aleph is in more of a stable state. If we should wait what aspects of Aleph could we work on to contribute to Aleph's growth that would be most helpful?

**Comment by shadowtime2000** [comment]
@Carthanial I don't think DevTools are really necessary for Aleph because there isn't really that much information it could provide. At the most it would tell the file that is being used for the route, the framework that is being used on the page, and the SSR hydrated data. I also don't think it is worthwhile to work on at these early stages of Aleph because a lot of things could change. This is something we can think about for the future though. Also, once Aleph becomes stable we might ourselves develop DevTools for it.

**Comment by ije** [comment]
@Carthanial cool, can you please tell what the tool do? what features include? currently alephjs is based on react, the react devtools is enough for me

**Comment by Carthanial** [comment]
Thanks for the replies! And apologies for the late one from me! We are looking to sink our teeth into a new technology and provide as much developer support as possible for said technology. We were in the early stages of doing research on Aleph and wanted to see if there was any way to get into the space while offering something worth while. What you said about Aleph being at such an early stage and a devtool right now would have negligible if any positive affect on workflow it what we were thinking would be a strong possibility. Would love to know if/when there are more updates! Looking forward to seeing Aleph grow!
