### ISSUE TITLE
Aleph cannot find react.ts in Alpha.22

### ISSUE THREAD

**Issue by aadamsx** [alephjs/aleph.js#222]
I started out on Aleph:
$ aleph --version  
aleph.js 0.3.0-alpha.12
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2

With and import map of:

```
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.12/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.12/",
        "react": "https://esm.sh/react@17.0.1",
        "react-dom": "https://esm.sh/react-dom@17.0.1"
    },
    "scopes": {}
}
```

And [moved](https://github.com/alephjs/aleph.js/issues/221#issuecomment-808975783) to ```alpha.22``` with the following command ```aleph upgrade```.  Since Aleph does not change the import map I manually changed it to:

```
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.22/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.22/",
        "react": "https://esm.sh/react@17.0.2",
        "react-dom": "https://esm.sh/react-dom@17.0.2"
    },
    "scopes": {}
}
```
When doing a ```aleph dev -reload``` and then an ```aleph dev``` I get the following error:

```
ERROR Fetch module 'https://deno.land/x/aleph@v0.3.0-alpha.22/react.ts': Not Found
```

=> And looking at ```https://deno.land/x/aleph@v0.3.0-alpha.22/``` ```react.ts``` is no longer there as it was in``` alpha.12``` but the complier is expecting it to be there on ```aleph dev -reload``` <=

**Comment by aadamsx** [comment]
Yeah, I started a new project based on aleph.12 only (not an upgrade from alpha.12):

Now import map:
```
{
  "imports": {
    "~/": "./",
    "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.22/",
    "framework": "https://deno.land/x/aleph@v0.3.0-alpha.22/framework/core/mod.ts",
    "framework:react": "https://deno.land/x/aleph@v0.3.0-alpha.22/framework/react/mod.ts",
    "react": "https://esm.sh/react@17.0.1",
    "react-dom": "https://esm.sh/react-dom@17.0.1"
  },
  "scopes": {}
}
```

but even when I copy this imort map back into my old code here: https://github.com/aadamsx/aleph-error where it started out as alpha.12, the transpiler is still looking for that react file's location like it's stuck on alpha.12:

ERROR Fetch module 'https://deno.land/x/aleph@v0.3.0-alpha.22/react.ts': Not Found

**Comment by ije** [comment]
@aadamsx currently aleph will resolve react to 17.0.1, i will improve this following the import map setting. alpha.22 includes some breaking changes, one is i moved the react.ts to /framework/react/mod.ts

**Comment by ije** [comment]
since i want to support other lib like vue at next stage, i don't want to put framework code in project root

**Comment by aadamsx** [comment]
@ije I'm interested in contributing to this project, if that's something you'd be okay with, will you DM (email) me with details on how to start (I see no email for you)?

**Comment by ije** [comment]
hi @aadamsx,

sorry for the late relay, vary grateful you are interested in this project. Alephjs is a vary young project that has many issues need to be improved. you are welcome to contribute on it.

at beginning i created a clone project of nextjs: https://github.com/ije/postjs, and i use it in my personal projects, it gives me a good view about fullstack framework in JAM-stack context. when deno 1.0 released i decide to create anthor nextjs in deno. after some hard works it can work as a mvp fullstack framework, i implemented the hmr and react fast refresh, page/api routing, builtin css/less importing, support markdown page out of the box, ts in deno of couse, even the esm.sh CDN for deno/browser. our current website is created by alephjs 0.2.

in 0.3 branch, i'm thinking more about alephjs's future and value, what different with nextjs? what it stand for? so i almost rewrite the total project, added plugin system, split react framework code to a stand-alone module that allows we suppport other UI library like vue at next stage, use swc instead of tsc to get better prefs and AST opration. so it is extreme unstable currently, but i think it should be more stable in deno 1.9 i hope.

again, thanks and you are welcome to conttribute on alephjs since it is a huge project, the most complex module is the https://github.com/alephjs/aleph.js/blob/master/server/app.ts, it is the server and project runtime manager, you can read it as a start.

**Comment by aadamsx** [comment]
@ije thanks for the feedback, it would be nice to get an idea of the process/event flow as well...

I'll clone and try to run it on a project to start.
