### ISSUE TITLE
Use import map

### ISSUE THREAD

**Issue by ije** [alephjs/aleph.js#260]
Context: https://github.com/alephjs/aleph.js/pull/258

**Comment by shadowtime2000** [comment]
Ok, so... I think this is a kind of bad idea. 

First of all, it doesn't provide that much benefit to us as developers.

So let's say we are using an import map and I add a dependency. I just add a line to the JSON file then I import it in code.

What if I added a dependency with `deps.ts`?

Just add a couple lines of code to `deps.ts` then import it.

Imports from `deps.ts` should be readable anyways so that you can still tell what is being imported.

Second of all, makes it harder to install/use. 

So... some people use the install script. Some people use the `deno install` command. Some people don't even install and use `deno run`. We would be distrupting the entire system and forcing people to use the install script. That wouldn't be great for people who use `deno run` so they don't install it or something.

**Comment by ije** [comment]
@shadowtime2000 make sense. i removed `deps.ts` because i found the cli bootstrap time is slow since there are lot of deps...maybe we can keep current url importing, it's ok for me.

**Comment by ije** [comment]
https://deno.land/x/land may is the solution.
